# Generated by Django 4.0 on 2022-06-27 21:11

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('education_title', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(help_text='Date when you start the Job')),
                ('end_date', models.DateTimeField(help_text='Date when you finish the Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateTimeField(help_text='Date when you start the Job')),
                ('end_date', models.DateTimeField(help_text='Date when you finish the Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('personal_email', models.EmailField(max_length=254)),
                ('description', models.TextField(default='A brief description about yourself', verbose_name='Description')),
                ('residential_address', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(default='COL', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Medellin', max_length=100, verbose_name='City')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+57324204242', max_length=30, region=None, verbose_name='Phone Number')),
                ('photography', models.ImageField(default='fotoperfil.jpeg', upload_to='', verbose_name='Profile Photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Gender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
