# Generated by Django 4.0 on 2022-06-25 23:17

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='residencial_city',
        ),
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(default='Medellin', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='resume',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'Not Binary')], default='NB', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+57324204242', max_length=30, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(default='A brief description about yourself', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='photography',
            field=models.ImageField(default='/profile_default.png', upload_to='', verbose_name='Profile Photo'),
        ),
    ]
