# Generated by Django 4.0 on 2022-06-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_resume_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='photography',
            field=models.ImageField(default='fotoperfil.jpeg', upload_to='', verbose_name='Profile Photo'),
        ),
    ]
