# Generated by Django 4.0 on 2022-06-24 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sys_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('form', models.CharField(default='Here the admin should be create a form', max_length=100)),
                ('file', models.CharField(default='pdf option', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when report is assigned')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when employee start in role')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when employee end in role')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when employee was assigned to the team')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('employee', models.ManyToManyField(related_name='teams', through='management.Employee_Team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('default_contract', models.CharField(default='Pdf option', max_length=100)),
                ('default_salary', models.FloatField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='management.department')),
                ('employee', models.ManyToManyField(related_name='roles', through='management.Employee_Role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('employee', models.ManyToManyField(related_name='reports', through='management.Employee_Report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee_team',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.team'),
        ),
        migrations.AddField(
            model_name='employee_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.role'),
        ),
        migrations.AddField(
            model_name='employee_report',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.report'),
        ),
        migrations.CreateModel(
            name='Employee_Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when employee start in department')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when employee end in department')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='employee',
            field=models.ManyToManyField(related_name='departments', through='management.Employee_Department', to=settings.AUTH_USER_MODEL),
        ),
    ]
