# Generated by Django 4.0 on 2022-06-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
