# Generated by Django 4.0 on 2022-06-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['is_active', 'first_name', 'last_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
