# Generated by Django 4.0 on 2022-06-24 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sys_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when you the company pays')),
                ('bonuses', models.FloatField(blank=True)),
                ('paper_pay', models.CharField(default='pdf option', help_text='Colilla de pago', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(help_text='Start of vacations')),
                ('end_date', models.DateTimeField(help_text='End of vacations')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacation', to='sys_admin.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialSecurity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('pension', models.CharField(default='pdf option?', max_length=100)),
                ('insurance', models.CharField(default='pdf option?', max_length=100)),
                ('mandatory_healthcare_provider', models.CharField(default='eps?', max_length=100)),
                ('private_healthcare_provider', models.CharField(blank=True, default='eps?', max_length=100)),
                ('note', models.TextField(default='The employee has no illnesses to report')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_security', to='sys_admin.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('amount', models.FloatField()),
                ('contract', models.CharField(default='pdf option or collila de pago?', max_length=100)),
                ('employee', models.ManyToManyField(related_name='salary', through='legal.Employee_Salary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.salary'),
        ),
    ]
