# Generated by Django 4.0 on 2022-06-25 22:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when employee start in department')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when employee end in department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('form', models.CharField(default='Here the admin should be create a form', max_length=100)),
                ('file', models.CharField(default='pdf option', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when report is assigned')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when employee start in role')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when employee end in role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when employee was assigned to the team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('default_contract', models.CharField(default='Pdf option', max_length=100)),
                ('default_salary', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
