# Generated by Django 4.0 on 2022-06-25 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sys_admin', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='employee',
            field=models.ManyToManyField(related_name='teams', through='management.Employee_Team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='management.department'),
        ),
        migrations.AddField(
            model_name='role',
            name='employee',
            field=models.ManyToManyField(related_name='roles', through='management.Employee_Role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='employee',
            field=models.ManyToManyField(related_name='reports', through='management.Employee_Report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee_team',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.employee'),
        ),
        migrations.AddField(
            model_name='employee_team',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.team'),
        ),
        migrations.AddField(
            model_name='employee_role',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.employee'),
        ),
        migrations.AddField(
            model_name='employee_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.role'),
        ),
        migrations.AddField(
            model_name='employee_report',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.employee'),
        ),
        migrations.AddField(
            model_name='employee_report',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.report'),
        ),
        migrations.AddField(
            model_name='employee_department',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department'),
        ),
        migrations.AddField(
            model_name='employee_department',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='employee',
            field=models.ManyToManyField(related_name='departments', through='management.Employee_Department', to=settings.AUTH_USER_MODEL),
        ),
    ]
