# Generated by Django 4.0 on 2022-06-24 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sys_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('personal_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('photography', models.CharField(blank=True, default='photo', max_length=100)),
                ('residential_address', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('residencial_city', models.CharField(max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='sys_admin.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateTimeField(help_text='Date when you start the Job')),
                ('end_date', models.DateTimeField(help_text='Date when you finish the Job')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='sys_admin.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('education_title', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(help_text='Date when you start the Job')),
                ('end_date', models.DateTimeField(help_text='Date when you finish the Job')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='sys_admin.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
