# Generated by Django 4.0 on 2022-06-29 23:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when you the company pays')),
                ('bonuses', models.FloatField(blank=True)),
                ('paper_pay', models.CharField(default='pdf option', help_text='Colilla de pago', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('amount', models.FloatField()),
                ('contract', models.CharField(default='pdf option or collila de pago?', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialSecurity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('pension', models.CharField(blank=True, default='pdf option?', max_length=100)),
                ('insurance', models.CharField(blank=True, default='pdf option?', max_length=100)),
                ('mandatory_healthcare_provider', models.CharField(blank=True, default='eps?', max_length=100)),
                ('private_healthcare_provider', models.CharField(blank=True, default='eps?', max_length=100)),
                ('note', models.TextField(default='The employee has no illnesses to report')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Social Security pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(help_text='Start of vacations')),
                ('end_date', models.DateTimeField(help_text='End of vacations')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
