# Generated by Django 4.0 on 2022-06-27 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal', '0001_initial'),
        ('sys_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation', to='sys_admin.employee'),
        ),
        migrations.AddField(
            model_name='socialsecurity',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialsecurity', to='sys_admin.employee'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ManyToManyField(related_name='salary', through='legal.Employee_Salary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.employee'),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.salary'),
        ),
    ]
